### ISSUE TITLE
[Bug]: TTGO_T-listeners build fails with TFT_eSPI v2.5.34 or later

### ISSUE THREAD

**Issue by Jocke4f** [josephdadams/TallyArbiter#618]
### What happened?

Building TTGO_T-listeners fails when `git clone https://github.com/Bodmer/TFT_eSPI/` is used in the workflow. The change in TFT_eSPI to use `#include "hal/gpio_ll.h"` breaks the building.

Forcing the build to use v2.5.33 is a temporary workaround, this was introduced in https://github.com/josephdadams/TallyArbiter/pull/617

This technical debt needs to be fixed but right now is the force use of v2.5.33 temporary way forward.

### Version

master

### Distribution

Source

### OS

MacOS

### Relevant log output

```shell
In file included from /home/runner/Arduino/libraries/Arduino_JSON/src/JSON.h:25,
                   from /home/runner/Arduino/libraries/Arduino_JSON/src/Arduino_JSON.h:23,
                   from /home/runner/work/TallyArbiter/TallyArbiter/listener_clients/TTGO_T-listener/TTGO_T-listener.ino:17:
  /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.11/tools/sdk/esp32/include/hal/esp32/include/hal/gpio_ll.h: In function 'void gpio_ll_get_intr_status_high(gpio_dev_t*, uint32_t, uint32_t*)':
  /home/runner/Arduino/libraries/Arduino_JSON/src/JSONVar.h:27:16: error: 'typeof_' was not declared in this scope
   #define typeof typeof_
                  ^~~~~~~
  /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.11/tools/sdk/esp32/include/hal/platform_port/include/hal/misc.h:54:5: note: in expansion of macro 'typeof'
       typeof(base_reg) temp_reg;                              \
       ^~~~~~
  /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.11/tools/sdk/esp32/include/hal/esp32/include/hal/gpio_ll.h:247:32: note: in expansion of macro 'HAL_FORCE_READ_U32_REG_FIELD'
       *status = (core_id == 0) ? HAL_FORCE_READ_U32_REG_FIELD(hw->pcpu_int1, intr) : HAL_FORCE_READ_U32_REG_FIELD(hw->acpu_int1, intr);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/runner/Arduino/libraries/Arduino_JSON/src/JSONVar.h:27:16: note: suggested alternative: 'typeof'
   #define typeof typeof_
                  ^~~~~~~
  /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.11/tools/sdk/esp32/include/hal/platform_port/include/hal/misc.h:54:5: note: in expansion of macro 'typeof'
       typeof(base_reg) temp_reg;                              \
       ^~~~~~
  /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.11/tools/sdk/esp32/include/hal/esp32/include/hal/gpio_ll.h:247:32: note: in expansion of macro 'HAL_FORCE_READ_U32_REG_FIELD'
       *status = (core_id == 0) ? HAL_FORCE_READ_U32_REG_FIELD(hw->pcpu_int1, intr) : HAL_FORCE_READ_U32_REG_FIELD(hw->acpu_int1, intr);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
